services:
  - type: web
    name: flask-postgres-app
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: flask-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: flask-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: flask-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: flask-db
          property: password
      - key: DB_PORT
        fromDatabase:
          name: flask-db
          property: port
databases:
  - name: flask-db